databases:
    - name: localcraftmarket
      databaseName: localcraftmarket
      user: localcraftmarket
      plan: free

services:
    - type: web
      name: localcraftmarket
      runtime: ruby
      plan: free
      buildCommand: './bin/render-build.sh'
      # preDeployCommand: "./bin/rails db:migrate" # preDeployCommand only available on paid instance types
      startCommand: './bin/rails server'
      envVars:
          - key: DATABASE_URL
            fromDatabase:
                name: localcraftmarket
                property: connectionString
          - key: RAILS_MASTER_KEY
            sync: false
          - key: WEB_CONCURRENCY
            value: 2 # sensible default